### ISSUE TITLE
context.Context support

### ISSUE THREAD

**Issue by mgurevin** [kurrik/oauth1a#19]
Is there a plan to add context.Context parameter for passing to HTTP requests? I can help with this if you'd like to add context support.

**Comment by kurrik** [comment]
Sure, I'm open to it!  I'd welcome a patch if you're willing to contribute one.

**Comment by mgurevin** [comment]
thanks for the answer, I will submit a PR soon

**Comment by mgurevin** [comment]
it's merged #20
